export const initialValues = {
  name: '',
  email: '',
  lang: 'en',
  password: '',
  expirationDate: false,
  expirationDateInput: '',
  setAuthority: false,
  can_print: true,
  can_download: true,
  pc_can_download: true,
  user_mobile_restriction: false,
  use_watermarks: false,
  ip_restriction: false,
  ipRestrictionInput: '',
  company_id: 0,
  permission: true,
  created_manually: 1,
};
